# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calculator.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63\x61lculator.proto\x12\x1b\x63om.example.calculator.grpc\"\"\n\nAddRequest\x12\t\n\x01\x61\x18\x01 \x01(\x01\x12\t\n\x01\x62\x18\x02 \x01(\x01\"\x1d\n\x0b\x41\x64\x64Response\x12\x0e\n\x06result\x18\x01 \x01(\x01\x32o\n\x11\x43\x61lculatorService\x12Z\n\x03\x61\x64\x64\x12\'.com.example.calculator.grpc.AddRequest\x1a(.com.example.calculator.grpc.AddResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'calculator_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ADDREQUEST']._serialized_start=49
  _globals['_ADDREQUEST']._serialized_end=83
  _globals['_ADDRESPONSE']._serialized_start=85
  _globals['_ADDRESPONSE']._serialized_end=114
  _globals['_CALCULATORSERVICE']._serialized_start=116
  _globals['_CALCULATORSERVICE']._serialized_end=227
# @@protoc_insertion_point(module_scope)
