# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import calculator_pb2 as calculator__pb2


class CalculatorServiceStub(object):
    """The calculator service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.add = channel.unary_unary(
                '/com.example.calculator.grpc.CalculatorService/add',
                request_serializer=calculator__pb2.AddRequest.SerializeToString,
                response_deserializer=calculator__pb2.AddResponse.FromString,
                )
        self.compareImages = channel.unary_unary(
                '/com.example.calculator.grpc.CalculatorService/compareImages',
                request_serializer=calculator__pb2.ImageComparisonRequest.SerializeToString,
                response_deserializer=calculator__pb2.ImageComparisonResponse.FromString,
                )


class CalculatorServiceServicer(object):
    """The calculator service definition
    """

    def add(self, request, context):
        """Add two numbers
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def compareImages(self, request, context):
        """Compare two images and check if they are the same person
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CalculatorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'add': grpc.unary_unary_rpc_method_handler(
                    servicer.add,
                    request_deserializer=calculator__pb2.AddRequest.FromString,
                    response_serializer=calculator__pb2.AddResponse.SerializeToString,
            ),
            'compareImages': grpc.unary_unary_rpc_method_handler(
                    servicer.compareImages,
                    request_deserializer=calculator__pb2.ImageComparisonRequest.FromString,
                    response_serializer=calculator__pb2.ImageComparisonResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'com.example.calculator.grpc.CalculatorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CalculatorService(object):
    """The calculator service definition
    """

    @staticmethod
    def add(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/com.example.calculator.grpc.CalculatorService/add',
            calculator__pb2.AddRequest.SerializeToString,
            calculator__pb2.AddResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def compareImages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/com.example.calculator.grpc.CalculatorService/compareImages',
            calculator__pb2.ImageComparisonRequest.SerializeToString,
            calculator__pb2.ImageComparisonResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
